logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.miniapp: debug
    cn.binarywang.wx.miniapp: debug
wx:
  miniapp:
    configs:
      - appid: wxeb9fb7d2851bee96
        secret: f3d148e5baecf1945ad7b29495184d59
        #        token: #微信小程序消息服务器配置的token
        #        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: Yuanyulou789!
    driver-class-name: com.mysql.jdbc.Driver
  data:
    elasticsearch:
      cluster-nodes: xx.67.xxx.xx:9300
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    host: xx.67.xxx.xx
    port: 6379
    password: 4BCq661sfd6n&Ru
    timeout: 1000
    jedis:
      pool:
        max-active: 1024
        max-wait: 10000
        max-idle: 200
        min-idle: 0

mybatis:
  # spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl